{
 "title": " NODE API ",
 "tags": [
  "ziv",
  "dash"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Float gauge ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "simple_float_gauge" }
   ]
  },
  {
   "title": "Int gauge ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "simple_int_gauge" }
   ]
  },
  {
   "title": "Int counter",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "simple_int_counter{instance=~\"168.62.161.227:8000\"}",
     "legendFormat": "Int counter"
    }
   ]
  },
  {
   "title": "Float counter",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "simple_float_counter{instance=~\"168.62.161.227:8000\"}",
     "legendFormat": "Float counter"
    }
   ]
  },
  {
   "title": "gauge metrics type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simple_float_gauge{instance=~\"168.62.161.227:8000\"}",
     "legendFormat": "Float gauge"
    },
    {
     "expr": "simple_int_gauge{instance=~\"168.62.161.227:8000\"}",
     "legendFormat": "Int gauge"
    }
   ]
  },
  {
   "title": "count metric type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simple_float_counter{instance=~\"168.62.161.227:8000\"}",
     "legendFormat": "Float counter"
    },
    {
     "expr": "simple_int_counter{instance=~\"168.62.161.227:8000\"}",
     "legendFormat": "Int counter "
    }
   ]
  }
 ]
}